DROP TABLE IF EXISTS TBL_ADDRESS;

DROP SEQUENCE IF EXISTS SEQ_ADDRESS_ID;
CREATE SEQUENCE IF NOT EXISTS SEQ_ADDRESS_ID START 1 INCREMENT 1 NO MAXVALUE CACHE 1;

CREATE TABLE TBL_ADDRESS(
	ID BIGINT NOT NULL DEFAULT NEXTVAL('SEQ_ADDRESS_ID'),
	TYPE VARCHAR(128) NOT NULL,
	NUMBER VARCHAR(128) NOT NULL,
	STREET VARCHAR(128) NOT NULL,
	UNIT VARCHAR(128) NOT NULL,
	CITY VARCHAR(128) NOT NULL,
	STATE VARCHAR(128) NOT NULL,
	ZIP_CODE VARCHAR(128) NOT NULL,
	IDENTIFICATION_ID BIGINT,
	STATUS VARCHAR(3),
	CREATED_BY VARCHAR(32)NOT NULL,
	CREATED_DATETIME TIMESTAMP(6) WITH TIME ZONE,
	MODIFIED_BY VARCHAR(32)NOT NULL,
	MODIFIED_DATETIME TIMESTAMP(6) WITH TIME ZONE,
	VERSION_NO SMALLINT,
	SOURCE VARCHAR(32)
);

DROP TRIGGER IF EXISTS TRG_INS_ADDRESS on TBL_ADDRESS;
CREATE TRIGGER TRG_INS_ADDRESS BEFORE INSERT ON TBL_ADDRESS
	FOR EACH ROW EXECUTE PROCEDURE FUNC_INS_SB();
	
DROP TRIGGER IF EXISTS TRG_UPD_ADDRESS on TBL_ADDRESS;
CREATE TRIGGER TRG_UPD_ADDRESS BEFORE UPDATE ON TBL_ADDRESS
	FOR EACH ROW EXECUTE PROCEDURE FUNC_UPD_SB();

