DROP TABLE IF EXISTS TBL_COMMUNICATION;

DROP SEQUENCE IF EXISTS SEQ_COMMUNICATION_ID;
CREATE SEQUENCE IF NOT EXISTS SEQ_COMMUNICATION_ID START 1 INCREMENT 1 NO MAXVALUE CACHE 1;

CREATE TABLE TBL_COMMUNICATION(
	ID BIGINT NOT NULL DEFAULT NEXTVAL('SEQ_COMMUNICATION_ID'),
	TYPE VARCHAR(129) NOT NULL,
	VALUE VARCHAR(130) NOT NULL,
	PREFERRED BOOLEAN,
	IDENTIFICATION_ID BIGINT,
	STATUS VARCHAR(3),
	CREATED_BY VARCHAR(32)NOT NULL,
	CREATED_DATETIME TIMESTAMP(6) WITH TIME ZONE,
	MODIFIED_BY VARCHAR(32)NOT NULL,
	MODIFIED_DATETIME TIMESTAMP(6) WITH TIME ZONE,
	VERSION_NO SMALLINT,
	SOURCE VARCHAR(32)
);

DROP TRIGGER IF EXISTS TRG_INS_COMMUNICATION on TBL_COMMUNICATION;
CREATE TRIGGER TRG_INS_COMMUNICATION BEFORE INSERT ON TBL_COMMUNICATION
	FOR EACH ROW EXECUTE PROCEDURE FUNC_INS_SB();
	
DROP TRIGGER IF EXISTS TRG_UPD_COMMUNICATION on TBL_COMMUNICATION;
CREATE TRIGGER TRG_UPD_COMMUNICATION BEFORE UPDATE ON TBL_COMMUNICATION
	FOR EACH ROW EXECUTE PROCEDURE FUNC_UPD_SB();

